config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  resources :password_resets

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'

  match '/signout', to: 'sessions#destroy', via: :delete

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_error_messages.html.erb
<!-- Check if there are any error messages -->
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			<!-- State how many error messages there are -->
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>

		<ul>
			<!-- Loop through each error message -->
			<% object.errors.full_messages.each do |msg| %>
				<!-- Create a new list item for each error message and display the error message within the list item -->
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>

	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  	<%= link_to gravatar_for(feed_item.user), feed_item.user %>

  	<span class="user">
    	<%= link_to feed_item.user.name, feed_item.user %>
  	</span>

    <%= render partial: 'shared/micropost_item', object: feed_item, as: 'thepost' %>
 </li>

app/views/shared/_home_not_signed_in.html.erb
<div class="center hero-unit">
	<h1>Welcome to the Sample App</h1>

	<h2>
	    This is the home page for the
	    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
	    sample application.
	</h2>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/shared/_home_signed_in.html.erb
<div class="row">
	<aside class="span4">
		<section>
			<%= render 'shared/user_info' %>
		</section>

		<section>
			<%= render 'shared/stats' %>
		</section>

		<section>
			<%= render 'shared/micropost_form' %>
		</section>
	</aside>

	<!-- Status Feed -->
	<div class="span8">
		<h3>Micropost Feed</h3>
		<%= render 'shared/feed' %>
	</div>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost..." %>
	</div>

	<p id="charsremaining" style="text-align: right"></p>

	<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_micropost_item.html.erb
<span class="content">
	<%= wrap(thepost.content) %>
</span>

<span class="timestamp">
	Posted <%= time_ago_in_words(thepost.created_at) %> ago.
</span>

<!-- Check if the user is the owner of the post -->
<% if current_user?(thepost.user) %>
	<!-- The user is, so give him the option to delete the post by placing a "delete" link next to it -->
	<%= link_to "delete", thepost, method: :delete, data: { confirm: "You sure?" }, title: "Delete this micropost" %>
<% end %>

app/views/shared/_stats.html.erb
<!-- Set @user to the current user when the user is on the home page -->
<% @user ||= current_user %>

<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		
		following
	</a>

	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>

		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 52 %>
</a>

<h1>
	<%= current_user.name %>
</h1>

<span>
	<%= link_to "view my profile", current_user %>
</span>

<span>
	<%= pluralize(current_user.microposts.count, "micropost") %>
</span>